#!/bin/sh

# $1 target package directory

package=$1
shift
options=$@

if [ ! -e ${package}/.ftm/config ]; then
	cd ${package}
	if [ -e 'configure' ]; then
		./configure ${options}
	elif [ -e 'Configure' ]; then
		./Configure ${options}
	elif [ -e 'CMakeLists.txt' ]; then
		cmake ${options} .
	else
		echo "error : Do not know to configuration"
		exit 1
	fi

	[ ! -e .ftm ] && mkdir .ftm

	echo `date` > .ftm/config

fi

